resources:
  - name: test-sam-app
    type: git
    source:
      uri: https://github.com/codelikesree/Test-sam-app.git
      branch: main

jobs:
  - name: deploy
    plan:
      - get: test-sam-app
        trigger: true
      - task: deploy
        file: test-sam-app/ci/deploy.yaml
